//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPMTool
{
    using System;
    using UnityEditor;
    using UnityEditor.PackageManager;
    using UnityEditor.PackageManager.Requests;
    using UnityEditor.PackageManager.UI;
    using UnityEngine.UIElements;
    using PackageInfo = UnityEditor.PackageManager.PackageInfo;
    
    
    [InitializeOnLoad()]
    public class UPMToolImporter : IPackageManagerExtension
    {
        
        public const string DisplayName = "UPM Tool";
        
        static UPMToolImporter()
        {
            PackageManagerExtensions.RegisterExtension(new UPMToolImporter());
        }
        
        public virtual VisualElement CreateExtensionUI()
        {
            VisualElement ve = null;
            return ve;
        }
        
        public virtual void OnPackageSelectionChange(PackageInfo packageInfo)
        {
        }
        
        public virtual void OnPackageAddedOrUpdated(PackageInfo packageInfo)
        {
        }
        
        public virtual void OnPackageRemoved(PackageInfo packageInfo)
        {
        }
    }
}
